import uglify     from 'uglify-js';
var props = uglify.readDefaultReservedFile().props;
props.push('define');
props.push('Content-Type');
props.push('Authorization');
props.push('Accept');
props.push('token');
props.push('title');
props.push('description');
props.push('registerdate');
props.push('lastlogindate');
props.push('lat');
props.push('lng');
props.push('price');
props.push('changes');
props.push('waiting');
props.push('installing');
props.push('onupdatefound');
props.push('waitUntil');
props.push('addAll');
props.push('keys');
props.push('filter');
props.push('request');
props.push('respondWith');
props.push('skipWaiting');
props.push('response_type');
props.push('scopes');

export default props;